# Generated by Django 6.0.2 on 2026-04-20 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='Backend.habit')),
            ],
        ),
    ]
